### ISSUE TITLE
Release-1.0 checklist

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#159]
- [x] Test last feature commit https://github.com/Musicoin/desktop/commit/ae5ef30def319d6d3594bc35abe8dcadad7c65e2 (on All OSs)
- [x] Resolve any bugs which may cause wallet to crash
- [x] Test again
- [x] Freeze commit hash
- [x] Release

**Comment by Archimedes1618** [comment]
you might want to hide that on Facebook until the "Latest Release" is up to date

https://www.facebook.com/notes/musicoin/musicoin-desktop-wallet-v10/2021429308097799/

**Comment by Varunram** [comment]
@Archimedes1618 Release-1.0 is ready for use, we're waiting for the official press release to update it on GitHub. You can download it over at builder.musicoin.org

**Comment by Varunram** [comment]
Version 1.0 released.
